    name: Rifts
    main: io.github.lancedh.rifts.Rifts
    version: 0.5
    authors: 
        - LanceDH   
    commands:
        place:
            description: Place the next piece of the maze.
            usage: /<command>
            permission: 
            permission-message: You don't have <permission>
        draw:
            description: Draw the freakin maze.
            usage: /<command>
            permission: 
            permission-message: You don't have <permission>
        gen:
            description: Build a maze of a specific size.
            usage: /<command> <size> <mobCount>
            permission: 
            permission-message: You don't have <permission>